#coding=utf-8
__author__ = 'egor'

"""
Script parameters:
    1: name of file with positive words, which were found by our algorithms (will be tested)
    2: name of file with negative words, which were found by our algorithms
    3: name of file with neutral words, which were found by our algorithms
    4: Big dictionary positive words filename
    5: Big dictionary negative words filename
    6: Big dictionary neutral words filename

While execution, you'll need to mark new for big dictionary words from console

Script will create three files in a working directory with names:
    'big_ext_pos.txt',    - new marked positive words
    'big_ext_neg.txt',    - new marked negative words
    'big_ext_neutral.txt' - new marked neutral words
"""

import sys


def read_pos(dict_to_add, filename):
    f = open(filename, 'r', encoding = "utf-8")
    for s in f:
        if s.strip(' \n') not in dict_to_add:
            dict_to_add[s.strip(' \n')] = 1
    f.close()


def read_neg(dict_to_add, filename):
    f = open(filename, 'r', encoding = "utf-8")
    for s in f:
        if s.strip(' \n') not in dict_to_add:
            dict_to_add[s.strip(' \n')] = -1
    f.close()


def read_neutral(dict_to_add, filename):
    f = open(filename, 'r', encoding = "utf-8")
    for s in f:
        if s.strip(' \n') not in dict_to_add:
            dict_to_add[s.strip(' \n')] = 0
    f.close()


if len(sys.argv) < 7:
    sys.exit("Bad arguments!")
   
big_dict = {}           # given big dictionary
big_ext_dict = {}       # new words to add
new_dict = {}           # dictionary, which were found by our algorithm

#reading dictionaries
read_pos(new_dict, sys.argv[1])
read_neg(new_dict, sys.argv[2])
read_neutral(new_dict, sys.argv[3])
read_pos(big_dict, sys.argv[4])
read_neg(big_dict, sys.argv[5])
read_neutral(big_dict, sys.argv[6])

quality_value = 0       # number of guessed words from big dictionary
	
# iterating through words from generated by algorithms dictionary and counting guessed words.	
for key in new_dict.keys():
    if key in big_dict and big_dict[key] == new_dict[key]:
        quality_value += 1
    elif key not in big_dict and key not in big_ext_dict:  # means, that we found a new word
        big_ext_dict[key] = 0

print('Quality value: ' + str(quality_value) + ' => '
      + str(quality_value * 100 / len(big_dict)) + '%')

f = open('big_ext_not_marked.txt', 'w', encoding = "utf-8")

for key in big_ext_dict:
    f.write(key + '\n')

f.close()
